node('jenkins-slave') {
    def newApp
    def registry = 'kumargaurav522/docker-test'
	stage('Git') {
		git 'https://github.com/kumargaurav522/node-pileline-script.git'
	}
	
    stage('Building image') {
        def buildName = registry + ":$BUILD_NUMBER"
		newApp = docker.build buildName
	}
}
