apiVersion: v1
kind: Service
metadata:
  name: sonarqube-service
  labels:
    app: sonarqube
spec:
  ports:
  - protocol: TCP
    name: sonarqube
    nodePort: 32000
    targetPort: 9000
    port: 9000   
  type: NodePort 
  selector:
    app: sonarqube
